spring.application.name=nexcommerce-api

server.port=8080
 

spring.datasource.url=jdbc:postgresql://localhost:5432/nexcommerce_db
spring.datasource.username=postgres
spring.datasource.password=nexpass
spring.datasource.driver-class-name=org.postgresql.Driver
 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=minha-chave-secreta-deve-ter-256-bits-ou-mais-aqui
app.jwt.expiration-ms=86400000
 
 
logging.level.root=INFO
logging.level.com.nexcommerce=DEBUG